jobs:
- job: Windows
  pool:
    vmImage: VS2017-Win2016
  steps:
    - task: 1ESLighthouseEng.PipelineArtifactCaching.RestoreCacheV1.RestoreCache@1
      inputs:
        keyfile: 'download_install_qt.ps1, azure-pipelines.yml'
        targetfolder: 'Qt/5.12.3'
        vstsFeed: '$(ArtifactFeed)'
    - task: PowerShell@2
      condition: ne(variables['CacheRestored'], 'true')
      inputs:
        filePath: download_install_qt.ps1
    - task: 1ESLighthouseEng.PipelineArtifactCaching.SaveCacheV1.SaveCache@1
      inputs:
        keyfile: 'download_install_qt.ps1, azure-pipelines.yml'
        targetfolder: 'Qt/5.12.3'
        vstsFeed: '$(ArtifactFeed)'
        condition: and(succeeded(), ne(variables['CacheRestored'], 'true'))