jobs:
- job: Windows
  pool:
    vmImage: VS2017-Win2016
  steps:
    - task: 1ESLighthouseEng.PipelineArtifactCaching.RestoreAndSaveCacheV1.RestoreAndSaveCache@1
      inputs:
        keyfile: 'download_install_qt.ps1'
        targetfolder: 'Qt'
        vstsFeed: '$(ArtifactFeed)'
    - task: PowerShell@2
      inputs:
        filePath: download_install_qt.ps1
        condition: ne(variables['CacheRestored'], 'true')